[package]
name = "vihaco-cpu"
edition = "2024"
description = "CPU/host component implementation for vihaco machines."
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
chumsky = { workspace = true }
codespan = "0.13.1"
eyre = { workspace = true }
log = "0.4.29"
vihaco = { workspace = true }
vihaco-parser = { workspace = true }
vihaco-parser-derive = { workspace = true }
