// SPDX-FileCopyrightText: 2026 The vihaco Authors
// SPDX-License-Identifier: MIT

use vihaco_abi::program::{Type, Value};
use vihaco_bytecode::{ConstantId, ContextHandle, SstSectionView};

use crate::host::{GetProgramInfo, ProgramCounter};
use crate::module::{FunctionInfo, LabelInfo, LocalModule, NoInfo, SourceSymbolInfo};

/// Allow a machine to load the SST data owned directly by its section.
///
/// When used with the [`vihaco_runtime_derive::composite`] macro, this hook runs before
/// generated child-section forwarding. Implement this for each composite to
/// make its own section behavior explicit, even when that behavior is a no-op.
pub trait LoadOwnSstSection<C> {
    fn load_own_sst_section<'bc>(&mut self, section: SstSectionView<'bc, C>) -> eyre::Result<()>;
}

/// Allow a machine to load an SST section completely.
///
/// For composites generated by [`vihaco_runtime_derive::composite`], this loads the
/// composite's own section through [`LoadOwnSstSection`] and then forwards
/// direct child sections to `#[loadable]` devices.
pub trait LoadSstSection<C> {
    fn load_sst_section<'bc>(&mut self, section: SstSectionView<'bc, C>) -> eyre::Result<()>;
}

/// Replace a program's loaded module, context, and program-counter state as one operation.
///
/// Implementations must complete any validation before mutating the program. The supplied
/// context becomes the context for the installed module, and a successful installation starts
/// execution at program counter zero.
pub trait InstallProgramModule<C> {
    type Module;

    fn install_program_module(
        &mut self,
        module: Self::Module,
        context: ContextHandle<C>,
    ) -> eyre::Result<()>;
}

/// Build the runtime module owned by a program container from resolved SST data.
///
/// [`LocalModule`] receives the standard implementation through [`ProgramImage`]. Custom
/// program containers may implement this capability to preserve their own module and metadata
/// representation while still using generated composite loading.
pub trait BuildProgramModule {
    type Instruction;
    type Value;
    type Type;
    type Info;
    type Module;

    fn empty_module() -> Self::Module;

    fn append_instructions(
        module: &mut Self::Module,
        instructions: impl IntoIterator<Item = Self::Instruction>,
    );

    fn instruction_count(module: &Self::Module) -> u32;

    fn add_function(module: &mut Self::Module, function: FunctionInfo<Self::Type>);

    fn add_label(module: &mut Self::Module, label: LabelInfo);

    fn add_source_symbol(module: &mut Self::Module, symbol: SourceSymbolInfo);

    fn intern_string(module: &mut Self::Module, value: String) -> u32;

    fn add_constant(module: &mut Self::Module, value: Self::Value) -> u32;

    fn set_main_function(module: &mut Self::Module, function: Option<u32>);

    fn finish(module: Self::Module) -> eyre::Result<Self::Module>;
}

#[derive(Debug, Clone)]
pub struct ProgramImage<I, C, V = Value, Ty = Type, Info = NoInfo> {
    pub module: LocalModule<I, V, Ty, Info>,
    pub context: Option<ContextHandle<C>>,
    pub pc: u32,
}

impl<I, C, V, Ty, Info: Default> Default for ProgramImage<I, C, V, Ty, Info> {
    fn default() -> Self {
        Self {
            module: LocalModule::default(),
            context: None,
            pc: 0,
        }
    }
}

impl<I, C, V, Ty, Info> ProgramImage<I, C, V, Ty, Info> {
    pub fn new() -> Self
    where
        Info: Default,
    {
        Self::default()
    }

    pub fn with_extra(extra: Info) -> Self {
        Self {
            module: LocalModule {
                code: Vec::new(),
                functions: Vec::new(),
                labels: Vec::new(),
                constants: Vec::new(),
                strings: Vec::new(),
                main_function: None,
                source_symbols: Vec::new(),
                extra,
            },
            context: None,
            pc: 0,
        }
    }

    pub fn context(&self) -> eyre::Result<&C> {
        self.context
            .as_ref()
            .map(ContextHandle::get)
            .ok_or_else(|| eyre::eyre!("program image has not been loaded with a context"))
    }
}

impl<I, C, V, Ty, Info> InstallProgramModule<C> for ProgramImage<I, C, V, Ty, Info> {
    type Module = LocalModule<I, V, Ty, Info>;

    fn install_program_module(
        &mut self,
        module: Self::Module,
        context: ContextHandle<C>,
    ) -> eyre::Result<()> {
        self.module = module;
        self.context = Some(context);
        self.pc = 0;
        Ok(())
    }
}

impl<I, C, V, Ty, Info: Default> BuildProgramModule for ProgramImage<I, C, V, Ty, Info> {
    type Instruction = I;
    type Value = V;
    type Type = Ty;
    type Info = Info;
    type Module = LocalModule<I, V, Ty, Info>;

    fn empty_module() -> Self::Module {
        LocalModule::default()
    }

    fn append_instructions(
        module: &mut Self::Module,
        instructions: impl IntoIterator<Item = Self::Instruction>,
    ) {
        module.code.extend(instructions);
    }

    fn instruction_count(module: &Self::Module) -> u32 {
        module.code.len() as u32
    }

    fn add_function(module: &mut Self::Module, function: FunctionInfo<Self::Type>) {
        module.functions.push(function);
    }

    fn add_label(module: &mut Self::Module, label: LabelInfo) {
        module.labels.push(label);
    }

    fn add_source_symbol(module: &mut Self::Module, symbol: SourceSymbolInfo) {
        module.source_symbols.push(symbol);
    }

    fn intern_string(module: &mut Self::Module, value: String) -> u32 {
        if let Some(index) = module
            .strings
            .iter()
            .position(|existing| existing == &value)
        {
            index as u32
        } else {
            let index = module.strings.len() as u32;
            module.strings.push(value);
            index
        }
    }

    fn add_constant(module: &mut Self::Module, value: Self::Value) -> u32 {
        let index = module.constants.len() as u32;
        module.constants.push(value);
        index
    }

    fn set_main_function(module: &mut Self::Module, function: Option<u32>) {
        module.main_function = function;
    }

    fn finish(module: Self::Module) -> eyre::Result<Self::Module> {
        Ok(module)
    }
}

impl<I, C, V, Ty, Info> ProgramCounter for ProgramImage<I, C, V, Ty, Info> {
    type Instruction = I;

    fn pc(&self) -> u32 {
        self.pc
    }

    fn pc_mut(&mut self) -> &mut u32 {
        &mut self.pc
    }

    fn get_instruction(&self, pc: u32) -> eyre::Result<&Self::Instruction> {
        self.module.code.get(pc as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "program counter out of bounds: {} (max {})",
                pc,
                self.module.code.len()
            ))
        })
    }
}

impl<I, C, V, Ty, Info> GetProgramInfo for ProgramImage<I, C, V, Ty, Info>
where
    Ty: Clone,
{
    type Type = Ty;
    type Value = V;

    fn get_function(&self, index: usize) -> eyre::Result<crate::module::FunctionInfo<Self::Type>> {
        self.module.functions.get(index).cloned().ok_or_else(|| {
            eyre::eyre!(format!(
                "function index out of bounds: {} (max {})",
                index,
                self.module.functions.len()
            ))
        })
    }

    fn get_string(&self, index: usize) -> eyre::Result<&String> {
        self.module.strings.get(index).ok_or_else(|| {
            eyre::eyre!(format!(
                "string index out of bounds: {} (max {})",
                index,
                self.module.strings.len()
            ))
        })
    }

    fn get_constant(&self, id: ConstantId) -> eyre::Result<&Self::Value> {
        self.module.constants.get(id.0 as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "constant index out of bounds: {} (max {})",
                id.0,
                self.module.constants.len()
            ))
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, Clone, PartialEq)]
    struct TestInstruction(u32);

    #[derive(Debug, Clone, PartialEq)]
    struct TestType;

    #[derive(Debug, Clone, Default, PartialEq)]
    struct TestInfo;

    #[test]
    fn installation_replaces_module_context_and_pc_together() {
        let old_context = ContextHandle::new("old");
        let new_context = ContextHandle::new("new");
        let mut image: ProgramImage<TestInstruction, &str, u8, TestType, TestInfo> = ProgramImage {
            module: LocalModule {
                code: vec![TestInstruction(1)],
                extra: TestInfo,
                ..LocalModule::default()
            },
            context: Some(old_context),
            pc: 7,
        };
        let module = LocalModule {
            code: vec![TestInstruction(2), TestInstruction(3)],
            extra: TestInfo,
            ..LocalModule::default()
        };

        image
            .install_program_module(module, new_context.clone())
            .unwrap();

        assert_eq!(
            image.module.code,
            vec![TestInstruction(2), TestInstruction(3)]
        );
        assert_eq!(image.context().unwrap(), &"new");
        assert!(image.context.as_ref().unwrap().ptr_eq(&new_context));
        assert_eq!(image.pc, 0);
    }

    #[test]
    fn program_counter_supports_non_bytecode_instructions() {
        let mut image: ProgramImage<TestInstruction, &str> = ProgramImage {
            module: LocalModule {
                code: vec![TestInstruction(7), TestInstruction(11)],
                ..LocalModule::default()
            },
            context: None,
            pc: 0,
        };

        assert_eq!(image.peek_instruction().unwrap(), &TestInstruction(7));
        assert_eq!(image.next_instruction().unwrap(), &TestInstruction(7));
        assert_eq!(image.pc(), 1);
        assert_eq!(image.next_instruction().unwrap(), &TestInstruction(11));
        assert_eq!(image.pc(), 2);
    }

    #[test]
    fn local_module_builder_appends_and_interns() {
        let mut module =
            <ProgramImage<TestInstruction, &str> as BuildProgramModule>::empty_module();
        <ProgramImage<TestInstruction, &str> as BuildProgramModule>::append_instructions(
            &mut module,
            [TestInstruction(7), TestInstruction(11)],
        );
        let first = <ProgramImage<TestInstruction, &str> as BuildProgramModule>::intern_string(
            &mut module,
            "main".to_owned(),
        );
        let second = <ProgramImage<TestInstruction, &str> as BuildProgramModule>::intern_string(
            &mut module,
            "main".to_owned(),
        );

        assert_eq!(module.code, vec![TestInstruction(7), TestInstruction(11)]);
        assert_eq!(first, 0);
        assert_eq!(second, first);
    }
}
