// SPDX-FileCopyrightText: 2026 The vihaco Authors
// SPDX-License-Identifier: MIT

// ===========================================================================================
// === AUTHOR: the machine declaration =======================================================
// ===========================================================================================
//
// The reusable `Cpu` composite plus the root `HeterogeneousMachine`. The route wiring below
// (`routes`, `Route`/`Handle`/`Observe` impls, per-route resolvers, and the step match) is written
// out so the complete composite boundary is visible at the invocation site.

// ===========================================================================================
// === GENERATED BY THE COMPOSITE MACRO =====================================================
// ===========================================================================================
//
// This entire section is the expansion of the `Cpu` composite and its five runtime routes. It is
// written out here so the generated ownership, routing, observation, and execution boundaries are
// directly readable.

struct Cpu {
    operand_stack: Stack,
    alu: ArithmeticUnit,
    channel: ChannelEndpoint<i64, SharedTransport<i64>>,
    debug: DebugTrace,
    program: Vec<RuntimeInstruction>,
    pc: usize,
}

#[derive(Debug, Clone, Copy)]
enum RuntimeInstruction {
    IntegerAdd(Add),
    IntegerSub(Sub),
    IntegerMul(Mul),
    Send(Send),
    Recv(Recv),
}

mod routes {
    #[derive(Debug, Clone, Copy, Default)]
    pub struct IntegerAdd;
    #[derive(Debug, Clone, Copy, Default)]
    pub struct IntegerSub;
    #[derive(Debug, Clone, Copy, Default)]
    pub struct IntegerMul;
    #[derive(Debug, Clone, Copy, Default)]
    pub struct Send;
    #[derive(Debug, Clone, Copy, Default)]
    pub struct Recv;
}

impl Route for routes::IntegerAdd {
    type Effect = ValueResult;
    type Error = CpuFault;
}

impl Route for routes::IntegerSub {
    type Effect = ValueResult;
    type Error = CpuFault;
}

impl Route for routes::IntegerMul {
    type Effect = ValueResult;
    type Error = CpuFault;
}

impl Handle<ValueResult, routes::IntegerAdd> for Cpu {
    type Error = CpuFault;

    fn handle(&mut self, effect: ValueResult) -> Result<(), CpuFault> {
        self.operand_stack.absorb(effect)?;
        Ok(())
    }
}

impl Handle<ValueResult, routes::IntegerSub> for Cpu {
    type Error = CpuFault;

    fn handle(&mut self, effect: ValueResult) -> Result<(), CpuFault> {
        self.operand_stack.absorb(effect)?;
        Ok(())
    }
}

impl Handle<ValueResult, routes::IntegerMul> for Cpu {
    type Error = CpuFault;

    fn handle(&mut self, effect: ValueResult) -> Result<(), CpuFault> {
        self.operand_stack.absorb(effect)?;
        Ok(())
    }
}

impl Route for routes::Send {
    type Effect = SendEffect;
    type Error = CpuFault;
}

impl Handle<SendEffect, routes::Send> for Cpu {
    type Error = CpuFault;

    fn handle(&mut self, effect: SendEffect) -> Result<(), CpuFault> {
        match effect {}
    }
}

impl Route for routes::Recv {
    type Effect = ReceiveEffect<i64>;
    type Error = CpuFault;
}

impl Handle<ReceiveEffect<i64>, routes::Recv> for Cpu {
    type Error = CpuFault;

    fn handle(&mut self, effect: ReceiveEffect<i64>) -> Result<(), CpuFault> {
        match effect {
            ReceiveEffect::Received(value) => self.operand_stack.push(value),
            ReceiveEffect::Parked(_) => {}
        }
        Ok(())
    }
}

impl TimedInstruction for RuntimeInstruction {
    fn local_cycles(&self) -> LocalCycles {
        match self {
            RuntimeInstruction::IntegerAdd(_)
            | RuntimeInstruction::IntegerSub(_)
            | RuntimeInstruction::IntegerMul(_)
            | RuntimeInstruction::Send(_)
            | RuntimeInstruction::Recv(_) => LocalCycles::ONE,
        }
    }
}

impl Cpu {
    fn fetch(&self) -> Option<RuntimeInstruction> {
        self.program.get(self.pc).copied()
    }

    fn finished(&self) -> bool {
        self.pc >= self.program.len() && !self.channel.is_parked()
    }

    fn is_parked(&self) -> bool {
        self.channel.is_parked()
    }

    // Keep the conversion explicit in generated route plumbing. It anchors the intended
    // machine-level fault type and gives users a direct diagnostic when a component or observer
    // is missing the corresponding `From<...> for CpuFault` conversion. For routes whose error is
    // already `CpuFault`, this becomes the identity `Into` conversion, so Clippy reports it as
    // useless; the suppression is limited to this generated dispatch boundary because the same
    // expansion must support both heterogeneous and identity conversions.
    #[allow(clippy::useless_conversion)]
    fn execute_generated(
        &mut self,
        instruction: &RuntimeInstruction,
    ) -> Result<Execution, CpuFault> {
        match instruction {
            RuntimeInstruction::IntegerAdd(instruction) => {
                let message = self.operand_stack.supply()?;
                let result = self.alu.execute(instruction, message)?;
                for effect in result.effects {
                    <DebugTrace as Observe<ValueResult, routes::IntegerAdd>>::observe(
                        &mut self.debug,
                        &effect,
                    )
                    .map_err(Into::<CpuFault>::into)?;
                    <Self as Handle<ValueResult, routes::IntegerAdd>>::handle(self, effect)
                        .map_err(Into::<CpuFault>::into)?;
                }
                Ok(result.execution)
            }
            RuntimeInstruction::IntegerSub(instruction) => {
                let message = self.operand_stack.supply()?;
                let result = self.alu.execute(instruction, message)?;
                for effect in result.effects {
                    <DebugTrace as Observe<ValueResult, routes::IntegerSub>>::observe(
                        &mut self.debug,
                        &effect,
                    )
                    .map_err(Into::<CpuFault>::into)?;
                    <Self as Handle<ValueResult, routes::IntegerSub>>::handle(self, effect)
                        .map_err(Into::<CpuFault>::into)?;
                }
                Ok(result.execution)
            }
            RuntimeInstruction::IntegerMul(instruction) => {
                let message = self.operand_stack.supply()?;
                let result = self.alu.execute(instruction, message)?;
                for effect in result.effects {
                    <DebugTrace as Observe<ValueResult, routes::IntegerMul>>::observe(
                        &mut self.debug,
                        &effect,
                    )
                    .map_err(Into::<CpuFault>::into)?;
                    <Self as Handle<ValueResult, routes::IntegerMul>>::handle(self, effect)
                        .map_err(Into::<CpuFault>::into)?;
                }
                Ok(result.execution)
            }
            RuntimeInstruction::Send(instruction) => {
                let message = self.operand_stack.supply()?;
                let result = self.channel.execute(instruction, message)?;
                for effect in result.effects {
                    <DebugTrace as Observe<SendEffect, routes::Send>>::observe(
                        &mut self.debug,
                        &effect,
                    )
                    .map_err(Into::<CpuFault>::into)?;
                    <Self as Handle<SendEffect, routes::Send>>::handle(self, effect)
                        .map_err(Into::<CpuFault>::into)?;
                }
                Ok(result.execution)
            }
            RuntimeInstruction::Recv(instruction) => {
                let result = self.channel.execute(instruction, NoMessage)?;
                for effect in result.effects {
                    <DebugTrace as Observe<ReceiveEffect<i64>, routes::Recv>>::observe(
                        &mut self.debug,
                        &effect,
                    )
                    .map_err(Into::<CpuFault>::into)?;
                    <Self as Handle<ReceiveEffect<i64>, routes::Recv>>::handle(self, effect)
                        .map_err(Into::<CpuFault>::into)?;
                }
                Ok(result.execution)
            }
        }
    }

    // This resume path uses the same explicit, generated error normalization as dispatch above;
    // some route instantiations reduce it to an identity conversion.
    #[allow(clippy::useless_conversion)]
    fn resume_receive_effects(
        &mut self,
        continuation: ReceiveContinuation,
        value: i64,
    ) -> Result<Execution, CpuFault> {
        let result = self.channel.resume(ReceiveCompletion {
            continuation,
            value,
        })?;
        for effect in result.effects {
            <DebugTrace as Observe<ReceiveEffect<i64>, routes::Recv>>::observe(
                &mut self.debug,
                &effect,
            )
            .map_err(Into::<CpuFault>::into)?;
            <Self as Handle<ReceiveEffect<i64>, routes::Recv>>::handle(self, effect)
                .map_err(Into::<CpuFault>::into)?;
        }
        Ok(result.execution)
    }

    /// Finish one instruction, advance the program counter when appropriate, and return owned
    /// child-local scheduling work. This is CPU-internal bookkeeping; the standard clocked
    /// boundary exposes only `step_at` and `resume`.
    fn complete_instruction(
        &mut self,
        global_tick: GlobalTick,
        instruction: &RuntimeInstruction,
        outcome: Execution,
        ticks_per_local_cycle: GlobalTicksPerLocalCycle,
    ) -> Result<Option<Schedule<CpuEvent>>, CpuFault> {
        if outcome == Execution::Complete {
            self.pc += 1;
        }

        if outcome == Execution::Parked {
            return Ok(None);
        }

        let start = self.next_boundary_at(global_tick, ticks_per_local_cycle)?;
        let duration = instruction
            .local_cycles()
            .checked_mul(ticks_per_local_cycle)?;
        let at = start
            .0
            .checked_add(duration.0)
            .map(GlobalTick)
            .ok_or(ClockFault::GlobalTickOverflow)?;
        if self.finished() {
            return Ok(None);
        }
        Ok(Some(Schedule {
            at,
            event: CpuEvent::RunNext,
        }))
    }
}

// ===========================================================================================
// === END GENERATED COMPOSITE SECTION =======================================================
// ===========================================================================================

#[derive(Debug, Clone, Copy)]
enum CpuEvent {
    RunNext,
}

impl ClockedComponent for Cpu {
    type Event = CpuEvent;
    type Completion = ReceiveCompletion<i64>;
    type Fault = CpuFault;

    fn step_at(
        &mut self,
        global_tick: GlobalTick,
        ticks_per_local_cycle: GlobalTicksPerLocalCycle,
    ) -> Result<Option<Schedule<CpuEvent>>, CpuFault> {
        let Some(instruction) = self.fetch() else {
            return Ok(None);
        };
        let execution = self.execute_generated(&instruction)?;
        self.complete_instruction(
            global_tick,
            &instruction,
            execution,
            ticks_per_local_cycle,
        )
    }

    fn resume(
        &mut self,
        completion: ReceiveCompletion<i64>,
        global_tick: GlobalTick,
        ticks_per_local_cycle: GlobalTicksPerLocalCycle,
    ) -> Result<Option<Schedule<CpuEvent>>, CpuFault> {
        let outcome = self.resume_receive_effects(completion.continuation, completion.value)?;
        let instruction = self.fetch().ok_or(CpuFault::MissingInstruction)?;
        self.complete_instruction(
            global_tick,
            &instruction,
            outcome,
            ticks_per_local_cycle,
        )
    }

    fn next_boundary_at(
        &self,
        global_tick: GlobalTick,
        ticks_per_local_cycle: GlobalTicksPerLocalCycle,
    ) -> Result<GlobalTick, CpuFault> {
        let ratio = ticks_per_local_cycle.0;
        let cycles = global_tick
            .0
            .checked_add(ratio - 1)
            .ok_or(CpuFault::Clock(ClockFault::GlobalTickOverflow))?
            / ratio;
        cycles
            .checked_mul(ratio)
            .map(GlobalTick)
            .ok_or(CpuFault::Clock(ClockFault::GlobalTickOverflow))
    }
}

// ===========================================================================================
// === GENERATED ERROR PLUMBING ===============================================================
// ===========================================================================================
//
// The composite macro supplies the route error conversions so generated pipeline code can use
// `?` across component boundaries.

/// Machine-level fault, with the `From` conversions generated for route plumbing.
#[derive(Debug)]
enum CpuFault {
    Stack(StackFault),
    Clock(ClockFault),
    UnknownEndpoint,
    MissingInstruction,
    MissingTiming,
}

impl From<StackFault> for CpuFault {
    fn from(fault: StackFault) -> Self {
        CpuFault::Stack(fault)
    }
}

impl From<std::convert::Infallible> for CpuFault {
    fn from(never: std::convert::Infallible) -> Self {
        match never {}
    }
}

impl From<ClockFault> for CpuFault {
    fn from(fault: ClockFault) -> Self {
        CpuFault::Clock(fault)
    }
}

// ===========================================================================================
// === END GENERATED ERROR PLUMBING ===========================================================
// ===========================================================================================
