[package]
name = "vihaco"
edition = "2024"
description = "Virtual ISA and machine framework for hybrid analog/digital quantum control orchestration."
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
byteorder = { workspace = true }
chumsky = { workspace = true }
codespan = "0.13.1"
colored = "3.0.0"
env_logger = "0.11.8"
eyre = { workspace = true }
log = "0.4.29"
smallvec = { workspace = true }
vihaco-abi = { workspace = true }
vihaco-bytecode = { workspace = true }
vihaco-module = { workspace = true }
vihaco-syntax = { workspace = true }
vihaco-parser = { workspace = true }
vihaco-parser-derive = { workspace = true }
vihaco-derive = { workspace = true }

[dev-dependencies]
trybuild = "1.0"
