[package]
name = "vihaco-bytecode"
edition = "2024"
description = "Bytecode/SST container format for vihaco: file headers, section trees, and the container codec."
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
byteorder = { workspace = true }
chumsky = { workspace = true }
eyre = { workspace = true }
vihaco-abi = { workspace = true }
