// SPDX-FileCopyrightText: 2026 The vihaco Authors
// SPDX-License-Identifier: MIT

use crate::{
    binary::{
        BytecodeFile, BytecodeSectionView, ConstantId, ContextHandle, SstFile, SstSectionView,
    },
    module::{Module, NoInfo},
    program::{ProgramContext, ProgramGlobals, Type, Value},
    traits::{self, GetProgramGlobal, ProgramCounter},
};

/// The input given to a bytecode-loadable machine.
#[derive(Debug)]
pub struct BytecodeLoadInput<'bc, C = ProgramContext> {
    pub section: BytecodeSectionView<'bc, C>,
}

impl<'bc, C> Clone for BytecodeLoadInput<'bc, C> {
    fn clone(&self) -> Self {
        Self {
            section: self.section.clone(),
        }
    }
}

impl<'bc, C> From<&'bc BytecodeFile<C>> for BytecodeLoadInput<'bc, C> {
    fn from(file: &'bc BytecodeFile<C>) -> Self {
        Self {
            section: file.root(),
        }
    }
}

impl<'bc, C> From<BytecodeSectionView<'bc, C>> for BytecodeLoadInput<'bc, C> {
    fn from(section: BytecodeSectionView<'bc, C>) -> Self {
        Self { section }
    }
}

/// The input given to an SST-loadable machine.
#[derive(Debug)]
pub struct SstLoadInput<'bc, C = ProgramContext> {
    pub section: SstSectionView<'bc, C>,
}

impl<'bc, C> Clone for SstLoadInput<'bc, C> {
    fn clone(&self) -> Self {
        Self {
            section: self.section.clone(),
        }
    }
}

impl<'bc, C> From<&'bc SstFile<C>> for SstLoadInput<'bc, C> {
    fn from(file: &'bc SstFile<C>) -> Self {
        Self {
            section: file.root(),
        }
    }
}

impl<'bc, C> From<SstSectionView<'bc, C>> for SstLoadInput<'bc, C> {
    fn from(section: SstSectionView<'bc, C>) -> Self {
        Self { section }
    }
}

/// Allow a machine to load the bytecode data owned directly by its section.
///
/// When used with the [`vihaco_derive::composite`] macro, this hook runs before
/// generated child-section forwarding. Implement this for each composite to
/// make its own section behavior explicit, even when that behavior is a no-op.
pub trait LoadOwnBytecodeSection<C = ProgramContext> {
    fn load_own_bytecode_section<'bc>(
        &mut self,
        input: BytecodeLoadInput<'bc, C>,
    ) -> eyre::Result<()>;
}

/// Allow a machine to load the SST data owned directly by its section.
///
/// When used with the [`vihaco_derive::composite`] macro, this hook runs before
/// generated child-section forwarding. Implement this for each composite to
/// make its own section behavior explicit, even when that behavior is a no-op.
pub trait LoadOwnSstSection<C = ProgramContext> {
    fn load_own_sst_section<'bc>(&mut self, input: SstLoadInput<'bc, C>) -> eyre::Result<()>;
}

/// Allow a machine to load a bytecode section completely.
///
/// For composites generated by [`vihaco_derive::composite`], this loads the
/// composite's own section through [`LoadOwnBytecodeSection`] and then forwards
/// direct child sections to `#[loadable]` devices.
pub trait LoadBytecodeSection<C = ProgramContext> {
    fn load_bytecode_section<'bc>(&mut self, input: BytecodeLoadInput<'bc, C>) -> eyre::Result<()>;
}

/// Allow a machine to load an SST section completely.
///
/// For composites generated by [`vihaco_derive::composite`], this loads the
/// composite's own section through [`LoadOwnSstSection`] and then forwards
/// direct child sections to `#[loadable]` devices.
pub trait LoadSstSection<C = ProgramContext> {
    fn load_sst_section<'bc>(&mut self, input: SstLoadInput<'bc, C>) -> eyre::Result<()>;
}

#[derive(Debug, Clone)]
pub struct ModuleProgramLoader<I, V = Value, Ty = Type, Info = NoInfo> {
    pub module: Module<I, V, Ty, Info>,
    pub pc: u32,
}

impl<I, V, Ty, Info: Default> Default for ModuleProgramLoader<I, V, Ty, Info> {
    fn default() -> Self {
        Self {
            module: Module::default(),
            pc: 0,
        }
    }
}

impl<I: traits::Instruction, V, Ty, Info> ProgramCounter for ModuleProgramLoader<I, V, Ty, Info> {
    type Instruction = I;

    fn pc(&self) -> u32 {
        self.pc
    }

    fn pc_mut(&mut self) -> &mut u32 {
        &mut self.pc
    }

    fn get_instruction(&self, pc: u32) -> eyre::Result<&Self::Instruction> {
        self.module.code.get(pc as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "program counter out of bounds: {} (max {})",
                pc,
                self.module.code.len()
            ))
        })
    }
}

impl<I: traits::Instruction, V, Ty, Info> GetProgramGlobal for ModuleProgramLoader<I, V, Ty, Info>
where
    Ty: Clone,
{
    type Type = Ty;
    type Value = V;

    fn get_function(&self, index: usize) -> eyre::Result<crate::module::FunctionInfo<Self::Type>> {
        self.module.functions.get(index).cloned().ok_or_else(|| {
            eyre::eyre!(format!(
                "function index out of bounds: {} (max {})",
                index,
                self.module.functions.len()
            ))
        })
    }

    fn get_string(&self, index: usize) -> eyre::Result<&String> {
        self.module.strings.get(index).ok_or_else(|| {
            eyre::eyre!(format!(
                "string index out of bounds: {} (max {})",
                index,
                self.module.strings.len()
            ))
        })
    }

    fn get_constant(&self, id: ConstantId) -> eyre::Result<&Self::Value> {
        self.module.constants.get(id.0 as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "constant index out of bounds: {} (max {})",
                id.0,
                self.module.constants.len()
            ))
        })
    }
}

#[derive(Debug, Clone)]
pub struct ProgramLoader<I, C = ProgramContext, Info = NoInfo> {
    pub code: Vec<I>,
    pub context: Option<ContextHandle<C>>,
    pub pc: u32,
    pub extra: Info,
}

impl<I, C, Info: Default> Default for ProgramLoader<I, C, Info> {
    fn default() -> Self {
        Self {
            code: Vec::new(),
            context: None,
            pc: 0,
            extra: Info::default(),
        }
    }
}

impl<I, C, Info> ProgramLoader<I, C, Info> {
    pub fn new() -> Self
    where
        Info: Default,
    {
        Self::default()
    }

    pub fn with_extra(extra: Info) -> Self {
        Self {
            code: Vec::new(),
            context: None,
            pc: 0,
            extra,
        }
    }

    pub fn context(&self) -> eyre::Result<&C> {
        self.context
            .as_ref()
            .map(ContextHandle::get)
            .ok_or_else(|| eyre::eyre!("bytecode program loader has not been loaded"))
    }
}

impl<I, C, Info> LoadBytecodeSection<C> for ProgramLoader<I, C, Info>
where
    I: traits::Instruction,
{
    fn load_bytecode_section<'bc>(&mut self, input: BytecodeLoadInput<'bc, C>) -> eyre::Result<()> {
        self.code = input.section.decode_instructions()?;
        self.context = Some(input.section.context_handle());
        self.pc = 0;
        Ok(())
    }
}

impl<I, C, Info> LoadSstSection<C> for ProgramLoader<I, C, Info>
where
    I: traits::Instruction,
    for<'src> I: vihaco_parser_core::Parse<'src>,
{
    fn load_sst_section<'bc>(&mut self, input: SstLoadInput<'bc, C>) -> eyre::Result<()> {
        self.code = input.section.parse_instructions()?;
        self.context = Some(input.section.context_handle());
        self.pc = 0;
        Ok(())
    }
}

impl<I: traits::Instruction, C, Info> ProgramCounter for ProgramLoader<I, C, Info> {
    type Instruction = I;

    fn pc(&self) -> u32 {
        self.pc
    }

    fn pc_mut(&mut self) -> &mut u32 {
        &mut self.pc
    }

    fn get_instruction(&self, pc: u32) -> eyre::Result<&Self::Instruction> {
        self.code.get(pc as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "program counter out of bounds: {} (max {})",
                pc,
                self.code.len()
            ))
        })
    }
}

impl<I, C, Info> GetProgramGlobal for ProgramLoader<I, C, Info>
where
    C: ProgramGlobals,
{
    type Type = C::Type;
    type Value = C::Value;

    fn get_function(&self, index: usize) -> eyre::Result<crate::module::FunctionInfo<Self::Type>> {
        self.context()?.get_function(index)
    }

    fn get_string(&self, index: usize) -> eyre::Result<&String> {
        self.context()?.get_string(index)
    }

    fn get_constant(&self, id: ConstantId) -> eyre::Result<&Self::Value> {
        self.context()?.get_constant(id)
    }
}
