// SPDX-FileCopyrightText: 2026 The vihaco Authors
// SPDX-License-Identifier: MIT

use crate::{
    binary::{BytecodeSectionView, ConstantId, ContextHandle, SstSectionView},
    module::{LocalModule, NoInfo},
    program::{ProgramGlobals, Type, Value},
    traits::{self, GetProgramGlobal, ProgramCounter},
};

/// Allow a machine to load the bytecode data owned directly by its section.
///
/// When used with the [`vihaco_derive::composite`] macro, this hook runs before
/// generated child-section forwarding. Implement this for each composite to
/// make its own section behavior explicit, even when that behavior is a no-op.
pub trait LoadOwnBytecodeSection<C> {
    fn load_own_bytecode_section<'bc>(
        &mut self,
        section: BytecodeSectionView<'bc, C>,
    ) -> eyre::Result<()>;
}

/// Allow a machine to load the SST data owned directly by its section.
///
/// When used with the [`vihaco_derive::composite`] macro, this hook runs before
/// generated child-section forwarding. Implement this for each composite to
/// make its own section behavior explicit, even when that behavior is a no-op.
pub trait LoadOwnSstSection<C> {
    fn load_own_sst_section<'bc>(&mut self, section: SstSectionView<'bc, C>) -> eyre::Result<()>;
}

/// Allow a machine to load a bytecode section completely.
///
/// For composites generated by [`vihaco_derive::composite`], this loads the
/// composite's own section through [`LoadOwnBytecodeSection`] and then forwards
/// direct child sections to `#[loadable]` devices.
pub trait LoadBytecodeSection<C> {
    fn load_bytecode_section<'bc>(
        &mut self,
        section: BytecodeSectionView<'bc, C>,
    ) -> eyre::Result<()>;
}

/// Allow a machine to load an SST section completely.
///
/// For composites generated by [`vihaco_derive::composite`], this loads the
/// composite's own section through [`LoadOwnSstSection`] and then forwards
/// direct child sections to `#[loadable]` devices.
pub trait LoadSstSection<C> {
    fn load_sst_section<'bc>(&mut self, section: SstSectionView<'bc, C>) -> eyre::Result<()>;
}

#[derive(Debug, Clone)]
pub struct ProgramImage<I, C, V = Value, Ty = Type, Info = NoInfo> {
    pub module: LocalModule<I, V, Ty, Info>,
    pub context: Option<ContextHandle<C>>,
    pub pc: u32,
}

impl<I, C, V, Ty, Info: Default> Default for ProgramImage<I, C, V, Ty, Info> {
    fn default() -> Self {
        Self {
            module: LocalModule::default(),
            context: None,
            pc: 0,
        }
    }
}

impl<I, C, V, Ty, Info> ProgramImage<I, C, V, Ty, Info> {
    pub fn new() -> Self
    where
        Info: Default,
    {
        Self::default()
    }

    pub fn with_extra(extra: Info) -> Self {
        Self {
            module: LocalModule {
                code: Vec::new(),
                functions: Vec::new(),
                labels: Vec::new(),
                constants: Vec::new(),
                strings: Vec::new(),
                main_function: None,
                source_symbols: Vec::new(),
                extra,
            },
            context: None,
            pc: 0,
        }
    }

    pub fn context(&self) -> eyre::Result<&C> {
        self.context
            .as_ref()
            .map(ContextHandle::get)
            .ok_or_else(|| eyre::eyre!("program image has not been loaded with a context"))
    }
}

impl<I: traits::Instruction, C, V, Ty, Info> ProgramCounter for ProgramImage<I, C, V, Ty, Info> {
    type Instruction = I;

    fn pc(&self) -> u32 {
        self.pc
    }

    fn pc_mut(&mut self) -> &mut u32 {
        &mut self.pc
    }

    fn get_instruction(&self, pc: u32) -> eyre::Result<&Self::Instruction> {
        self.module.code.get(pc as usize).ok_or_else(|| {
            eyre::eyre!(format!(
                "program counter out of bounds: {} (max {})",
                pc,
                self.module.code.len()
            ))
        })
    }
}

impl<I: traits::Instruction, C, V, Ty, Info> GetProgramGlobal for ProgramImage<I, C, V, Ty, Info>
where
    Ty: Clone,
    C: ProgramGlobals<Type = Ty, Value = V>,
{
    type Type = Ty;
    type Value = V;

    fn get_function(&self, index: usize) -> eyre::Result<crate::module::FunctionInfo<Self::Type>> {
        if let Some(context) = &self.context {
            context.get().get_function(index)
        } else {
            self.module.functions.get(index).cloned().ok_or_else(|| {
                eyre::eyre!(format!(
                    "function index out of bounds: {} (max {})",
                    index,
                    self.module.functions.len()
                ))
            })
        }
    }

    fn get_string(&self, index: usize) -> eyre::Result<&String> {
        if let Some(context) = &self.context {
            context.get().get_string(index)
        } else {
            self.module.strings.get(index).ok_or_else(|| {
                eyre::eyre!(format!(
                    "string index out of bounds: {} (max {})",
                    index,
                    self.module.strings.len()
                ))
            })
        }
    }

    fn get_constant(&self, id: ConstantId) -> eyre::Result<&Self::Value> {
        if let Some(context) = &self.context {
            context.get().get_constant(id)
        } else {
            self.module.constants.get(id.0 as usize).ok_or_else(|| {
                eyre::eyre!(format!(
                    "constant index out of bounds: {} (max {})",
                    id.0,
                    self.module.constants.len()
                ))
            })
        }
    }
}
